# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
# Test comment

title: FunGen-xQTL Consortium
author: The NIH/NIA Alzheimer's Disease Sequencing Project Functional Genomics xQTL Consortium
logo: website/xqtl_wf.png
copyright: 2021+, FunGen xQTL Analysis Working Group
only_build_toc_files: true


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: website/xqtl_pipelines.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - website/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/statfungen/xqtl-protocol  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_edit_page_button: true 
  extra_navbar: Supported by <a href="https://www.nia.nih.gov/research/ad-genetics">NIH NIA</a> 

launch_buttons:
  binderhub_url: ""
